/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ChatForm.java
 *
 * Created on Oct 29, 2011, 10:58:00 AM
 */
package UserInterface;

import ChatUtil.ChatController;
import ChatUtil.ChatListener;
import FX.Skype;
import FX.Twitter;
import achive.AchiveMain;
import achive.ArchiveEntity;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.InetSocketAddress;
import java.net.Socket;
import java.net.URISyntaxException;
import java.util.Collection;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.application.Platform;
import javafx.stage.Stage;
import javax.swing.ImageIcon;
import javax.swing.JList;
import org.jivesoftware.smack.Chat;
import org.jivesoftware.smack.Connection;
import org.jivesoftware.smack.MessageListener;
import org.jivesoftware.smack.XMPPConnection;
import org.jivesoftware.smack.XMPPException;
import org.jivesoftware.smack.packet.Message;

/**
 *
 * @author Parvaneh
 */
public class ChatForm extends javax.swing.JFrame {

    private static ContactInfoCollectionListModel listmodel;
    private Connection gmailConnection;

    public static ContactInfoCollectionListModel getListmodel() {
        return listmodel;
    }

    public static void setListmodel(ContactInfoCollectionListModel listmodel) {
        ChatForm.listmodel = listmodel;
    }

    /**
     * Creates new form ChatForm
     */
    public ChatForm() {
        initComponents();
        new ChatListener().start();
    }
    Image img;

    public ChatForm(ContactInfoCollectionListModel listmodel) {
        ChatForm.listmodel = listmodel;

        initComponents();
        new ChatListener().start();
    }

    public void rersizeImage() {
        BufferedImage resizedImage = new BufferedImage(80, 80, BufferedImage.TYPE_INT_RGB);
        Graphics2D g = resizedImage.createGraphics();
        g.drawImage(img, 0, 0, 80, 80, null);
        g.dispose();
        jLabel2.setIcon(new ImageIcon(resizedImage.getScaledInstance(80, 80, 0)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        basicInformationPanel = new javax.swing.JPanel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        statusMessageField = new javax.swing.JTextField();
        statusComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        addFriendLabel = new javax.swing.JLabel();
        searchContactsField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        contactsList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        changeStatusMenu = new javax.swing.JMenu();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem4 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        settingsMenuItem = new javax.swing.JMenuItem();
        signOutMenuItem = new javax.swing.JMenuItem();
        Contacts = new javax.swing.JMenu();
        Actions = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        Help = new javax.swing.JMenu();
        helpMenuItem = new javax.swing.JMenuItem();
        aboutMneuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ciao! Chat");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(21, 51, 173));

        jPanel2.setBackground(new java.awt.Color(21, 51, 173));

        basicInformationPanel.setBackground(new java.awt.Color(255, 255, 255));

        firstNameLabel.setFont(new java.awt.Font("Arial", 1, 12));
        firstNameLabel.setForeground(new java.awt.Color(21, 51, 173));
        firstNameLabel.setText("FirstName");

        lastNameLabel.setFont(new java.awt.Font("Arial", 1, 12));
        lastNameLabel.setForeground(new java.awt.Color(21, 51, 173));
        lastNameLabel.setText("LastName");

        statusMessageField.setFont(new java.awt.Font("Tahoma", 2, 11));
        statusMessageField.setText("Status Message");
        statusMessageField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(21, 51, 173), 2));
        statusMessageField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statusMessageFieldMouseClicked(evt);
            }
        });
        statusMessageField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusMessageFieldActionPerformed(evt);
            }
        });
        statusMessageField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                statusMessageFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                statusMessageFieldFocusLost(evt);
            }
        });
        statusMessageField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                statusMessageFieldKeyPressed(evt);
            }
        });

        statusComboBox.setForeground(new java.awt.Color(21, 51, 173));
        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Online", "Busy", "Away", "Invisible" }));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/profilePicSmall-icon.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel2.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel2.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout basicInformationPanelLayout = new javax.swing.GroupLayout(basicInformationPanel);
        basicInformationPanel.setLayout(basicInformationPanelLayout);
        basicInformationPanelLayout.setHorizontalGroup(
            basicInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basicInformationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(basicInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(basicInformationPanelLayout.createSequentialGroup()
                        .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lastNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(statusMessageField, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                .addContainerGap())
        );
        basicInformationPanelLayout.setVerticalGroup(
            basicInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basicInformationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(basicInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basicInformationPanelLayout.createSequentialGroup()
                        .addGroup(basicInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameLabel)
                            .addComponent(lastNameLabel)
                            .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(statusMessageField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basicInformationPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        addFriendLabel.setFont(new java.awt.Font("Arial", 0, 11));
        addFriendLabel.setText("Add friends");
        addFriendLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addFriendLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addFriendLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addFriendLabelMouseExited(evt);
            }
        });

        searchContactsField.setFont(new java.awt.Font("Comic Sans MS", 2, 11));
        searchContactsField.setText("Find someone in my contact list");
        searchContactsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchContactsFieldActionPerformed(evt);
            }
        });
        searchContactsField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchContactsFieldKeyPressed(evt);
            }
        });

        contactsList.setModel(listmodel);
        contactsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactsListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(contactsList);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/addfriend-icon.jpg"))); // NOI18N

        jButton1.setText("History");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addFriendLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(searchContactsField, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addFriendLabel)
                            .addComponent(jButton1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchContactsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/skype.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/facebook-icon.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/im-icon-gtalk.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/twitter.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basicInformationPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addContainerGap(14, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(basicInformationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(276, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(268, 268, 268))
        );

        MenuBar.setBackground(new java.awt.Color(255, 179, 0));

        File.setBackground(new java.awt.Color(255, 179, 0));
        File.setForeground(new java.awt.Color(21, 51, 173));
        File.setText("File");

        changeStatusMenu.setBackground(new java.awt.Color(255, 179, 0));
        changeStatusMenu.setForeground(new java.awt.Color(21, 51, 173));
        changeStatusMenu.setText("Change Status");

        jRadioButtonMenuItem2.setBackground(new java.awt.Color(255, 179, 0));
        jRadioButtonMenuItem2.setForeground(new java.awt.Color(21, 51, 173));
        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("Online");
        changeStatusMenu.add(jRadioButtonMenuItem2);

        jRadioButtonMenuItem3.setBackground(new java.awt.Color(255, 179, 0));
        jRadioButtonMenuItem3.setForeground(new java.awt.Color(21, 51, 173));
        jRadioButtonMenuItem3.setText("Busy");
        changeStatusMenu.add(jRadioButtonMenuItem3);

        jRadioButtonMenuItem4.setBackground(new java.awt.Color(255, 179, 0));
        jRadioButtonMenuItem4.setForeground(new java.awt.Color(21, 51, 173));
        jRadioButtonMenuItem4.setText("Away");
        changeStatusMenu.add(jRadioButtonMenuItem4);

        jRadioButtonMenuItem1.setBackground(new java.awt.Color(255, 179, 0));
        jRadioButtonMenuItem1.setForeground(new java.awt.Color(21, 51, 173));
        jRadioButtonMenuItem1.setText("Invisible");
        changeStatusMenu.add(jRadioButtonMenuItem1);

        File.add(changeStatusMenu);

        settingsMenuItem.setBackground(new java.awt.Color(255, 179, 0));
        settingsMenuItem.setForeground(new java.awt.Color(21, 51, 173));
        settingsMenuItem.setText("Settings");
        File.add(settingsMenuItem);

        signOutMenuItem.setBackground(new java.awt.Color(255, 179, 0));
        signOutMenuItem.setForeground(new java.awt.Color(21, 51, 173));
        signOutMenuItem.setText("Sign Out");
        signOutMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signOutMenuItemMouseClicked(evt);
            }
        });
        signOutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutMenuItemActionPerformed(evt);
            }
        });
        File.add(signOutMenuItem);

        MenuBar.add(File);

        Contacts.setBackground(new java.awt.Color(255, 179, 0));
        Contacts.setForeground(new java.awt.Color(21, 51, 173));
        Contacts.setText("Contacts");
        MenuBar.add(Contacts);

        Actions.setBackground(new java.awt.Color(255, 179, 0));
        Actions.setForeground(new java.awt.Color(21, 51, 173));
        Actions.setText("Actions");

        jMenuItem1.setText("Profile Picture");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Actions.add(jMenuItem1);

        MenuBar.add(Actions);

        Help.setBackground(new java.awt.Color(255, 179, 0));
        Help.setForeground(new java.awt.Color(21, 51, 173));
        Help.setText("Help");

        helpMenuItem.setBackground(new java.awt.Color(255, 179, 0));
        helpMenuItem.setForeground(new java.awt.Color(21, 51, 173));
        helpMenuItem.setText("Ciao! Help");
        Help.add(helpMenuItem);

        aboutMneuItem.setBackground(new java.awt.Color(255, 179, 0));
        aboutMneuItem.setForeground(new java.awt.Color(21, 51, 173));
        aboutMneuItem.setText("About");
        Help.add(aboutMneuItem);

        MenuBar.add(Help);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void statusMessageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusMessageFieldActionPerformed
}//GEN-LAST:event_statusMessageFieldActionPerformed

private void signOutMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signOutMenuItemMouseClicked
}//GEN-LAST:event_signOutMenuItemMouseClicked

private void signOutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutMenuItemActionPerformed
    new File("profilepic.jpg").delete();
    this.dispose();
    MainForm mainform = new MainForm();
    mainform.setVisible(true);
}//GEN-LAST:event_signOutMenuItemActionPerformed

private void statusMessageFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_statusMessageFieldFocusGained
}//GEN-LAST:event_statusMessageFieldFocusGained

private void statusMessageFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statusMessageFieldMouseClicked
    statusMessageField.setEditable(true);
    statusMessageField.setText("");
}//GEN-LAST:event_statusMessageFieldMouseClicked

private void statusMessageFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_statusMessageFieldKeyPressed
    switch (evt.getKeyCode()) {
        case java.awt.event.KeyEvent.VK_ENTER:
            statusMessageField.setEditable(false);

            break;
    }
}//GEN-LAST:event_statusMessageFieldKeyPressed

private void statusMessageFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_statusMessageFieldFocusLost
}//GEN-LAST:event_statusMessageFieldFocusLost

private void addFriendLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addFriendLabelMouseEntered
    addFriendLabel.setForeground(new Color(255, 179, 0));
}//GEN-LAST:event_addFriendLabelMouseEntered

private void addFriendLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addFriendLabelMouseExited
    addFriendLabel.setForeground(new Color(0, 0, 0));
}//GEN-LAST:event_addFriendLabelMouseExited

private void searchContactsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchContactsFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_searchContactsFieldActionPerformed

private void addFriendLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addFriendLabelMouseClicked
    AddFriends addfriends = new AddFriends();
    addfriends.setVisible(true);
    SearchID searchid = new SearchID();
    searchid.setVisible(true);
}//GEN-LAST:event_addFriendLabelMouseClicked

private void searchContactsFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchContactsFieldKeyPressed

    switch (evt.getKeyCode()) {
        case java.awt.event.KeyEvent.VK_ENTER:

            break;
    }
}//GEN-LAST:event_searchContactsFieldKeyPressed

    private void contactsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactsListMouseClicked
        if (evt.getClickCount() == 2) {
            int index = contactsList.locationToIndex(evt.getPoint());
            String recep = (String) contactsList.getModel().getElementAt(index);
            ChatController.newChat(recep);
            System.out.println("1");
        }
    }//GEN-LAST:event_contactsListMouseClicked

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained

        contactsList.updateUI();
    }//GEN-LAST:event_formFocusGained

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus

        contactsList.updateUI();
    }//GEN-LAST:event_formWindowGainedFocus

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            AchiveMain.main(null);
        } catch (IOException ex) {
            Logger.getLogger(ChatForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new UploadForm(this).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        gmailConnection = new XMPPConnection("google.com");
        try {
            gmailConnection.connect();
        } catch (XMPPException ex) {
            Logger.getLogger(ChatForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        new Thread(new Runnable() {

            @Override
            public void run() {
                Platform.runLater(new Runnable() {

                    @Override
                    public void run() {
                        FX.Gtalk gl = new FX.Gtalk(gmailConnection);
                        Stage stage = new Stage();
                        try {
                            gl.start(stage);
                        } catch (Exception ex) {
                            Logger.getLogger(ChatForm.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                });
            }
        }).start();

        //jButton2.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        new Thread(new Runnable() {

            @Override
            public void run() {
                Platform.runLater(new Runnable() {

                    @Override
                    public void run() {
                        Twitter twitter = new Twitter();
                        Stage stage = new Stage();
                        twitter.start(stage);
                    }
                });
            }
        }).start();

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        try {
            new Facebook().setVisible(true);
        } catch (URISyntaxException ex) {
            Logger.getLogger(ChatForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ChatForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        new Thread(new Runnable() {

            public void run() {
                try {
                    Runtime.getRuntime().exec("resources\\skype\\windows-x86-skypekit-novideo_4.0.2.1195_710188\\bin\\windows-x86\\windows-x86-skypekit-novideo.exe");
                } catch (IOException ex) {
                    Logger.getLogger(ChatForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }).start();
        Platform.runLater(new Runnable() {

            @Override
            public void run() {
                Skype fxSkype = new Skype();
                Stage s = new Stage();
                try {
                    fxSkype.start(s);
                } catch (Exception ex) {
                    Logger.getLogger(ChatForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                ChatForm c = new ChatForm();
                c.setVisible(true);
            }
        });
    }
    //public String searchContacts;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Actions;
    private javax.swing.JMenu Contacts;
    private javax.swing.JMenu File;
    private javax.swing.JMenu Help;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem aboutMneuItem;
    private javax.swing.JLabel addFriendLabel;
    private javax.swing.JPanel basicInformationPanel;
    private javax.swing.JMenu changeStatusMenu;
    private javax.swing.JList contactsList;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JMenuItem helpMenuItem;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField searchContactsField;
    private javax.swing.JMenuItem settingsMenuItem;
    private javax.swing.JMenuItem signOutMenuItem;
    private javax.swing.JComboBox statusComboBox;
    private javax.swing.JTextField statusMessageField;
    // End of variables declaration//GEN-END:variables

    public void setUserInfo(String[] infos) {
        firstNameLabel.setText(infos[0]);
        lastNameLabel.setText(infos[1]);
    }

    public String getUserInfo() {
        return firstNameLabel.getText() + " " + lastNameLabel.getText();
    }

    void setGModel(ContactInfoCollectionListModel contactInfoCollectionListModel) {
    }

    public void profilepicUpdate(Image img) throws InterruptedException {
        this.img = img;
        rersizeImage();
    }
}
