/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CreateAccountForm.java
 *
 * Created on Oct 28, 2011, 8:01:28 PM
 */
package UserInterface;

import Authentication.authControl;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.NamingException;
import javax.swing.JOptionPane;

/**
 *
 * @author Parvaneh
 */
public class CreateAccountForm extends javax.swing.JFrame {

    String day;
    String month;
    String year;
    boolean buttonGroup = false;

    /** Creates new form CreateAccountForm */
    public CreateAccountForm() {
        initComponents();
        jProgressBar1.setVisible(false);
        connectingLabel.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        IDlabel = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        confirmPassLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        lengthLimitLabel = new javax.swing.JLabel();
        securityQuestionBox = new javax.swing.JComboBox();
        securityQuestionField = new javax.swing.JTextField();
        confirmPassField = new javax.swing.JPasswordField();
        reenterPassLabel = new javax.swing.JLabel();
        enterPassLabel = new javax.swing.JLabel();
        questionLabel = new javax.swing.JLabel();
        matchPassLabel = new javax.swing.JLabel();
        passLengthLabel = new javax.swing.JLabel();
        enterIDLabel = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        genderLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        femaleButton = new javax.swing.JRadioButton();
        maleButton = new javax.swing.JRadioButton();
        birthdayLabel = new javax.swing.JLabel();
        yearTextField = new javax.swing.JTextField();
        monthTextField = new javax.swing.JTextField();
        dayTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        enterEmailLabel = new javax.swing.JLabel();
        enterNameLabel = new javax.swing.JLabel();
        numericDateLabel = new javax.swing.JLabel();
        invalidMailLabel = new javax.swing.JLabel();
        dayLabel = new javax.swing.JLabel();
        monthLabel = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        sexErrorLabel = new javax.swing.JLabel();
        requiredFieldsLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        connectingLabel = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create new Ciao! Chat account");

        jPanel1.setBackground(new java.awt.Color(255, 179, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        jPanel2.setBackground(new java.awt.Color(21, 51, 173));

        jPanel3.setBackground(new java.awt.Color(255, 179, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        jLabel1.setForeground(new java.awt.Color(255, 179, 0));
        jLabel1.setText("Account Information");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        jLabel2.setForeground(new java.awt.Color(255, 179, 0));
        jLabel2.setText("Personal Information");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel1)
                .addGap(124, 124, 124)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(jLabel2)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        IDlabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        IDlabel.setText("* Ciao ! ID :");

        idTextField.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldActionPerformed(evt);
            }
        });
        idTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                idTextFieldFocusLost(evt);
            }
        });

        passwordLabel.setFont(new java.awt.Font("Calibri", 0, 14));
        passwordLabel.setText("* Password : ");

        confirmPassLabel.setFont(new java.awt.Font("Calibri", 0, 14));
        confirmPassLabel.setText("* Confirm password :");

        passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFieldFocusLost(evt);
            }
        });

        lengthLimitLabel.setFont(new java.awt.Font("Arial", 0, 11));
        lengthLimitLabel.setForeground(new java.awt.Color(255, 0, 0));
        lengthLimitLabel.setText("at least 6 characters");

        securityQuestionBox.setFont(new java.awt.Font("Arial", 0, 12));
        securityQuestionBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "What was the name of your best childhood friend?", "What is your favorite food?", "What is your pet's name?", "What is the name of your favorite book?", "Where did you spend your honeymoon?" }));
        securityQuestionBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                securityQuestionBoxActionPerformed(evt);
            }
        });

        securityQuestionField.setFont(new java.awt.Font("Calibri", 0, 12));
        securityQuestionField.setForeground(new java.awt.Color(51, 51, 51));
        securityQuestionField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                securityQuestionFieldMouseClicked(evt);
            }
        });

        confirmPassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPassFieldActionPerformed(evt);
            }
        });
        confirmPassField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                confirmPassFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                confirmPassFieldFocusLost(evt);
            }
        });

        reenterPassLabel.setFont(new java.awt.Font("Arial", 1, 11));
        reenterPassLabel.setForeground(new java.awt.Color(21, 51, 173));

        enterPassLabel.setFont(new java.awt.Font("Arial", 1, 11));
        enterPassLabel.setForeground(new java.awt.Color(21, 51, 173));

        questionLabel.setFont(new java.awt.Font("Arial", 1, 11));
        questionLabel.setForeground(new java.awt.Color(21, 51, 173));

        matchPassLabel.setFont(new java.awt.Font("Arial", 1, 11));
        matchPassLabel.setForeground(new java.awt.Color(21, 51, 173));

        passLengthLabel.setFont(new java.awt.Font("Arial", 1, 11));
        passLengthLabel.setForeground(new java.awt.Color(21, 51, 173));

        enterIDLabel.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        enterIDLabel.setForeground(new java.awt.Color(21, 51, 173));

        jButton2.setText("Check");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(securityQuestionField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(IDlabel)
                                .addComponent(passwordLabel))
                            .addGap(71, 71, 71)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(passwordField)
                                .addComponent(idTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                .addComponent(lengthLimitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(confirmPassField)))
                        .addComponent(confirmPassLabel, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(securityQuestionBox, 0, 354, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(questionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(passLengthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(matchPassLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(reenterPassLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(enterPassLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(enterIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enterIDLabel)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(IDlabel)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(passLengthLabel))
                            .addComponent(enterPassLabel)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(passwordLabel)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lengthLimitLabel))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(confirmPassLabel)
                            .addComponent(confirmPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reenterPassLabel)
                            .addComponent(matchPassLabel))))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(securityQuestionBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(securityQuestionField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(180, 180, 180))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        nameLabel.setFont(new java.awt.Font("Calibri", 0, 14));
        nameLabel.setText("* Name :");

        firstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameFieldActionPerformed(evt);
            }
        });

        lastNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameFieldActionPerformed(evt);
            }
        });

        genderLabel.setFont(new java.awt.Font("Calibri", 0, 14));
        genderLabel.setText("* Gender :");

        firstNameLabel.setText("First");

        lastNameLabel.setText("Last");

        femaleButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(femaleButton);
        femaleButton.setFont(new java.awt.Font("Calibri", 0, 12));
        femaleButton.setText("Female");
        femaleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                femaleButtonMouseClicked(evt);
            }
        });
        femaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleButtonActionPerformed(evt);
            }
        });

        maleButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(maleButton);
        maleButton.setFont(new java.awt.Font("Calibri", 0, 12));
        maleButton.setText("Male");
        maleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maleButtonMouseClicked(evt);
            }
        });
        maleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleButtonActionPerformed(evt);
            }
        });

        birthdayLabel.setFont(new java.awt.Font("Calibri", 0, 14));
        birthdayLabel.setText("   Birthday :");

        yearTextField.setFont(new java.awt.Font("Calibri", 0, 12));
        yearTextField.setForeground(new java.awt.Color(51, 51, 51));
        yearTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        yearTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yearTextFieldMouseClicked(evt);
            }
        });
        yearTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearTextFieldActionPerformed(evt);
            }
        });
        yearTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                yearTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                yearTextFieldFocusLost(evt);
            }
        });

        monthTextField.setFont(new java.awt.Font("Calibri", 0, 12));
        monthTextField.setForeground(new java.awt.Color(51, 51, 51));
        monthTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        monthTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monthTextFieldMouseClicked(evt);
            }
        });
        monthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthTextFieldActionPerformed(evt);
            }
        });
        monthTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                monthTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                monthTextFieldFocusLost(evt);
            }
        });

        dayTextField.setFont(new java.awt.Font("Calibri", 0, 12));
        dayTextField.setForeground(new java.awt.Color(51, 51, 51));
        dayTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dayTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dayTextFieldMouseClicked(evt);
            }
        });
        dayTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dayTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dayTextFieldFocusLost(evt);
            }
        });

        jLabel12.setText("/");

        jLabel13.setText("/");

        emailLabel.setFont(new java.awt.Font("Calibri", 0, 14));
        emailLabel.setText("* Email :");

        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });
        emailTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailTextFieldFocusLost(evt);
            }
        });

        enterEmailLabel.setFont(new java.awt.Font("Arial", 1, 11));
        enterEmailLabel.setForeground(new java.awt.Color(21, 51, 173));

        enterNameLabel.setFont(new java.awt.Font("Arial", 1, 11));
        enterNameLabel.setForeground(new java.awt.Color(21, 51, 173));

        numericDateLabel.setBackground(new java.awt.Color(255, 255, 255));
        numericDateLabel.setFont(new java.awt.Font("Arial", 1, 11));
        numericDateLabel.setForeground(new java.awt.Color(21, 51, 173));

        invalidMailLabel.setFont(new java.awt.Font("Arial", 1, 11));
        invalidMailLabel.setForeground(new java.awt.Color(21, 51, 173));

        dayLabel.setFont(new java.awt.Font("Arial", 0, 11));
        dayLabel.setForeground(new java.awt.Color(255, 0, 0));
        dayLabel.setText("Day");

        monthLabel.setFont(new java.awt.Font("Arial", 0, 11));
        monthLabel.setForeground(new java.awt.Color(255, 0, 0));
        monthLabel.setText("Month");

        yearLabel.setFont(new java.awt.Font("Arial", 0, 11));
        yearLabel.setForeground(new java.awt.Color(255, 0, 0));
        yearLabel.setText("Year");

        sexErrorLabel.setFont(new java.awt.Font("Arial", 1, 11));
        sexErrorLabel.setForeground(new java.awt.Color(21, 51, 173));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(emailLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(nameLabel)
                                .addGap(95, 95, 95))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(genderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(birthdayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(firstNameField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(firstNameLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(femaleButton, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNameLabel)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(maleButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(sexErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(lastNameField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(enterNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(invalidMailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(enterEmailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(dayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dayLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(monthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(monthLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(yearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(numericDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(yearLabel))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(lastNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterNameLabel))
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maleButton)
                    .addComponent(femaleButton)
                    .addComponent(genderLabel)
                    .addComponent(sexErrorLabel))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(monthTextField, 0, 0, Short.MAX_VALUE)
                            .addComponent(jLabel13)
                            .addComponent(yearTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                            .addComponent(numericDateLabel))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dayLabel)
                            .addComponent(monthLabel)
                            .addComponent(yearLabel))
                        .addGap(6, 6, 6))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(birthdayLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterEmailLabel)
                    .addComponent(invalidMailLabel))
                .addContainerGap())
        );

        requiredFieldsLabel.setFont(new java.awt.Font("Calibri", 1, 14));
        requiredFieldsLabel.setForeground(new java.awt.Color(255, 0, 0));
        requiredFieldsLabel.setText("* Required Fields");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(21, 51, 173));
        jButton1.setText("Create Account");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        connectingLabel.setFont(new java.awt.Font("Tahoma", 1, 12));
        connectingLabel.setForeground(new java.awt.Color(21, 51, 173));
        connectingLabel.setText("Connecting");

        jProgressBar1.setBackground(new java.awt.Color(21, 51, 173));
        jProgressBar1.setForeground(new java.awt.Color(255, 179, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(requiredFieldsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(connectingLabel)
                        .addGap(163, 163, 163))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(connectingLabel)
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(requiredFieldsLabel)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed
// TODO @Tannaz implement a function that checks the availability of a username
     /*       try {
    String stringSearch = idTextField.getText();
    // Open the file c:\test.txt as a buffered reader
    BufferedReader bf = new BufferedReader(new FileReader("?.txt"));
    
    // Start a line count and declare a string to hold our current line.
    int linecount = 0;
    String line;
    
    // Loop through each line, stashing the line into our line variable.
    while (( line = bf.readLine()) != null){
    // Increment the count and find the index of the word
    linecount++;
    int indexfound = line.indexOf(stringSearch);
    
    // If greater than -1, means we found the word
    if (indexfound > -1) {
    enterIDLabel.setText("Already exists!");  
    }
    }
    
    // Close the file after done searching
    bf.close();
    }
    catch (IOException e) {
    System.out.println("IO Error Occurred: " + e.toString());
    }
     */
}//GEN-LAST:event_idTextFieldActionPerformed

private void idTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idTextFieldFocusLost
}//GEN-LAST:event_idTextFieldFocusLost

private void passwordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusGained
    enterPassLabel.setText("");
}//GEN-LAST:event_passwordFieldFocusGained

private void passwordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusLost
    if (passwordField.getText().length() < 6) {
        enterPassLabel.setText("At least 6 characters");
    }
}//GEN-LAST:event_passwordFieldFocusLost

private void securityQuestionBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_securityQuestionBoxActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_securityQuestionBoxActionPerformed

private void securityQuestionFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_securityQuestionFieldMouseClicked
// TODO add your handling code here:
}//GEN-LAST:event_securityQuestionFieldMouseClicked

private void confirmPassFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPassFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_confirmPassFieldActionPerformed

private void confirmPassFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmPassFieldFocusGained
    matchPassLabel.setText("");
}//GEN-LAST:event_confirmPassFieldFocusGained

private void confirmPassFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmPassFieldFocusLost
    if (!(confirmPassField.getText().equals(passwordField.getText()))) {
        reenterPassLabel.setText("password does not match");
    }
}//GEN-LAST:event_confirmPassFieldFocusLost

private void firstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_firstNameFieldActionPerformed

private void lastNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_lastNameFieldActionPerformed

private void femaleButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_femaleButtonMouseClicked
    // TODO add your handling code here:
}//GEN-LAST:event_femaleButtonMouseClicked

private void femaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleButtonActionPerformed
    buttonGroup = true;
}//GEN-LAST:event_femaleButtonActionPerformed

private void maleButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maleButtonMouseClicked
    buttonGroup = true;
}//GEN-LAST:event_maleButtonMouseClicked

private void yearTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yearTextFieldMouseClicked
// TODO add your handling code here:
}//GEN-LAST:event_yearTextFieldMouseClicked

private void yearTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_yearTextFieldActionPerformed

private void yearTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_yearTextFieldFocusGained
    numericDateLabel.setText("");
}//GEN-LAST:event_yearTextFieldFocusGained

private void yearTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_yearTextFieldFocusLost
    try {
        year = dayTextField.getText();
        Integer.parseInt(year);
    } catch (NumberFormatException e) {
        numericDateLabel.setText("Invalid Date");
    }
}//GEN-LAST:event_yearTextFieldFocusLost

private void monthTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monthTextFieldMouseClicked
// TODO add your handling code here:
}//GEN-LAST:event_monthTextFieldMouseClicked

private void monthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_monthTextFieldActionPerformed

private void monthTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_monthTextFieldFocusGained
    numericDateLabel.setText("");
}//GEN-LAST:event_monthTextFieldFocusGained

private void monthTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_monthTextFieldFocusLost
    try {
        month = dayTextField.getText();
        Integer.parseInt(month);
    } catch (NumberFormatException e) {
        numericDateLabel.setText("Invalid Date");
    }
}//GEN-LAST:event_monthTextFieldFocusLost

private void dayTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dayTextFieldMouseClicked
// TODO add your handling code here:
}//GEN-LAST:event_dayTextFieldMouseClicked

private void dayTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dayTextFieldFocusGained
    numericDateLabel.setText("");
}//GEN-LAST:event_dayTextFieldFocusGained

private void dayTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dayTextFieldFocusLost
    try {
        day = dayTextField.getText();
        Integer.parseInt(day);
    } catch (NumberFormatException e) {
        numericDateLabel.setText("Invalid Date");
    }
}//GEN-LAST:event_dayTextFieldFocusLost

private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_emailTextFieldActionPerformed

private void emailTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextFieldFocusGained
    enterEmailLabel.setText("");
    invalidMailLabel.setText("");
}//GEN-LAST:event_emailTextFieldFocusGained

private void emailTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextFieldFocusLost

    if (!ValidateEmail.isEmailValid(emailTextField.getText())) {
        invalidMailLabel.setText("Invalid Email Address");
    }
}//GEN-LAST:event_emailTextFieldFocusLost

private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
// TODO add your handling code here:
}//GEN-LAST:event_jButton1MouseClicked

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    boolean anyError = false;
    enterIDLabel.setText("");
    reenterPassLabel.setText("");
    sexErrorLabel.setText("");
    enterPassLabel.setText("");
    questionLabel.setText("");
    enterEmailLabel.setText("");
    enterNameLabel.setText("");
    enterEmailLabel.setText("");
    invalidMailLabel.setText("");

    if (idTextField.getText().equals("")) {
        enterIDLabel.setText("Enter a Username");
        anyError = true;
    }
    if (securityQuestionField.getText().equals("")) {
        questionLabel.setText("Don't forget the sequrity question! ");
        anyError = true;
    }
    if (firstNameField.getText().equals("") || lastNameField.getText().equals("")) {
        enterNameLabel.setText("Enter your name");
        anyError = true;
    }

    if (!ValidateEmail.isEmailValid(emailTextField.getText())) {
        invalidMailLabel.setText("Invalid Email Address");
        anyError = true;
    }else if (emailTextField.getText().equals("") ) {
    enterEmailLabel.setText("We need your Email");
    anyError = true;
    }

    if (buttonGroup == false) {
        sexErrorLabel.setText("your Sex?");
        anyError = true;
    }
    if (passwordField.getText().length() < 6) {
        enterPassLabel.setText("At least 6 characters");
        anyError = true;
    }else if (passwordField.getText().equals("")) {
        enterPassLabel.setText("Choose a password");
        anyError = true;
    }
    if (!(confirmPassField.getText().equals(passwordField.getText()))) {
        reenterPassLabel.setText("password does not match");
        anyError = true;
    }else if (confirmPassField.getText().equals("")) {
        reenterPassLabel.setText("Reenter your password");
        anyError = true;
    }
    if (!anyError) {
        jProgressBar1.setIndeterminate(true);
        jProgressBar1.setVisible(true);
        connectingLabel.setVisible(true);
        new Thread(new Runnable() {

            public void run() {
                    if (authControl.usernameTaken(idTextField.getText())) {
                        enterIDLabel.setText("This username is not available!");
                    } else {
                        if (authControl.signUp(idTextField.getText(), passwordField.getPassword(), securityQuestionBox.getSelectedIndex(), securityQuestionField.getText(), firstNameField.getText(), lastNameField.getText(), maleButton.isSelected(), dayTextField.getText(), monthTextField.getText(), yearTextField.getText(), emailTextField.getText())) {
                            JOptionPane.showMessageDialog(jButton1,
                                    "Your account has been created successfully.");
                            dispose();
                        }
                    }
                    jProgressBar1.setIndeterminate(false);
                    jProgressBar1.setVisible(false);
                    connectingLabel.setVisible(false);
            }
        }).start();
    }
}//GEN-LAST:event_jButton1ActionPerformed

private void maleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleButtonActionPerformed
    buttonGroup = true;
}//GEN-LAST:event_maleButtonActionPerformed

private void idTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idTextFieldFocusGained
enterIDLabel.setText("");
}//GEN-LAST:event_idTextFieldFocusGained

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            if(authControl.usernameTaken(idTextField.getText()))
                enterIDLabel.setText("Not available");
            else
                enterIDLabel.setText("ID available");
}//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CreateAccountForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDlabel;
    private javax.swing.JLabel birthdayLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPasswordField confirmPassField;
    private javax.swing.JLabel confirmPassLabel;
    private javax.swing.JLabel connectingLabel;
    private javax.swing.JLabel dayLabel;
    private javax.swing.JTextField dayTextField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel enterEmailLabel;
    private javax.swing.JLabel enterIDLabel;
    private javax.swing.JLabel enterNameLabel;
    private javax.swing.JLabel enterPassLabel;
    private javax.swing.JRadioButton femaleButton;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel invalidMailLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JLabel lengthLimitLabel;
    private javax.swing.JRadioButton maleButton;
    private javax.swing.JLabel matchPassLabel;
    private javax.swing.JLabel monthLabel;
    private javax.swing.JTextField monthTextField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel numericDateLabel;
    private javax.swing.JLabel passLengthLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel questionLabel;
    private javax.swing.JLabel reenterPassLabel;
    private javax.swing.JLabel requiredFieldsLabel;
    private javax.swing.JComboBox securityQuestionBox;
    private javax.swing.JTextField securityQuestionField;
    private javax.swing.JLabel sexErrorLabel;
    private javax.swing.JLabel yearLabel;
    private javax.swing.JTextField yearTextField;
    // End of variables declaration//GEN-END:variables
}
